spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
          auto-add-partitions: true
      bindings:
        order-in-0:
          destination: com.github.dericksm.orderservice.order
          group: notificationServiceGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
        paymentRejected-in-0:
          destination: com.github.dericksm.paymentService.paymentRejected
          group: notificationServiceGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
        paymentConfirmed-in-0:
          destination: com.github.dericksm.paymentService.paymentConfirmed
          group: notificationServiceGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
    function:
      definition: order;paymentRejected;paymentConfirmed
  main:
    allow-bean-definition-overriding: true
server:
  port: 8084

