spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
          auto-add-partitions: true
          auto-create-topics: true
      bindings:
        order-in-0:
          destination: com.github.dericksm.orderservice.order
          group: paymentServiceGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
        stockReserveRejected-in-0:
          destination: com.github.dericksm.productservice.reserveRejected
          group: paymentServiceGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
        paymentRejected-out-0:
          destination: com.github.dericksm.paymentService.paymentRejected
          group: paymentServiceGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
        paymentConfirmed-out-0:
          destination: com.github.dericksm.paymentService.paymentConfirmed
          group: paymentServiceGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
    function:
      definition: order;reserveRejected
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: 
      database: storedatabase
      auto-index-creation: true
server:
  port: 8082

