spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
          auto-add-partitions: true
      bindings:
        order-out-0:
          destination: com.github.dericksm.orderservice.order
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 2
        releaseStock-out-0:
          destination: com.github.dericksm.orderservice.release-stock
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 2
        stockReservedRejected-in-0:
          destination: com.github.dericksm.productservice.reserve-rejected
          group: orderServiceGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
        stockConfirmedRejected-in-0:
          destination: com.github.dericksm.productservice.reserve-confirmed
          group: orderServiceGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
        paymentRejected-int-0:
          destination: com.github.dericksm.paymentService.payment-rejected
          group: orderServiceGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
        paymentConfirmed-int-0:
          destination: com.github.dericksm.paymentService.payment-confirmed
          group: orderServiceGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
    schema-registry-client:
      endpoint: http://${SCHEMA_REGISTRY_HOST:localhost}:${SCHEMA_REGISTRY_PORT:8081}
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb+srv://dsm:dsm@cluster0.ryeut.mongodb.net/?retryWrites=true&w=majority
      database: storedatabase
