spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:29092}
          auto-add-partitions: true
      bindings:
        order-in-0:
          destination: com.github.dericksm.orderservice.order
          group: productServiceGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
        releaseStock-in-0:
          destination: com.github.dericksm.orderservice.release-stock
          group: productServiceGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
        stockReserveRejected-out-0:
          destination: com.github.dericksm.productservice.reserve-rejected
          group: productServiceGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
        stockReserveConfirmed-out-0:
          destination: com.github.dericksm.productservice.reserve-confirmed
          group: productServiceGroup
          consumer:
            max-attempts: 4
            back-off-initial-interval: 10000
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb+srv://dsm:dsm@cluster0.ryeut.mongodb.net/?retryWrites=true&w=majority
      database: storedatabase
      auto-index-creation: true
server:
  port: 8081

